default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000


development:
  adapter: postgresql
  encoding: unicode
  database: ffs_logistics_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: ffs_logistics_test
  pool: 5
  timeout: 5000
